# Generated by Django 2.1.2 on 2018-10-24 09:41

import atoms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['title'],
            },
            bases=(models.Model, atoms.models.UIDMixin),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
            bases=(models.Model, atoms.models.UIDMixin),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atoms.Item')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('zoom', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('atoms.item',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atoms.Item')),
                ('url', models.URLField(max_length=512)),
                ('credit', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
            bases=('atoms.item',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='atoms.Item')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('atoms.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.ManyToManyField(blank=True, to='atoms.Feature'),
        ),
        migrations.AddField(
            model_name='item',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='_item_items_+', to='atoms.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_atoms.item_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atoms.Source'),
        ),
    ]
