# Generated by Django 2.1.2 on 2018-10-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atoms', '0002_delete_model_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='polymorphic_ctype',
        ),
    ]
