# Generated by Django 2.1.2 on 2018-10-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
        ('atoms', '0003_remove_polymorphic_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='document_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='themes.Document'),
            preserve_default=False,
        ),
    ]
